Repository catalyzt-tech/RetroPGF-Hub, pull requests merged in 2024-10, with the labels that each got.

#43 [RPGF-95] Migrate frontend data path to Worker
  app/(transparent_navbar)/explore/Cpage.tsx
  app/(transparent_navbar)/explore/page.tsx
  app/(white_navbar)/explore/RetroPGF5/RetroType5.d.ts
  app/(white_navbar)/explore/RetroPGF5/[name]/_component/_Project/ImpactStatementSection.tsx
  app/(white_navbar)/explore/RetroPGF5/[name]/page.tsx
  app/(white_navbar)/explore/RetroPGF5/_component/Tab/Filter/DialogFilter.tsx
  app/(white_navbar)/explore/RetroPGF5/_component/Tab/ProjectTab.tsx
  app/(white_navbar)/explore/RetroPGF5/page.tsx
  app/lib/realtime.ts
  pnpm-lock.yaml
  public/sitemap-0.xml
Labels: enhancement, ready to review

#44 [RPGF-79] Add Project / Application Status
  app/(white_navbar)/explore/RetroPGF5/Cpage.tsx
  app/(white_navbar)/explore/RetroPGF5/RetroType5.d.ts
  app/(white_navbar)/explore/RetroPGF5/_component/DynamicCard.tsx
  app/(white_navbar)/explore/RetroPGF5/_component/Tab/Filter/PriceModelDisclosure.tsx
  app/(white_navbar)/explore/RetroPGF5/_component/Tab/ProjectTab.tsx
  app/(white_navbar)/explore/RetroPGF5/page.tsx
  app/component/Card/RetroCardRound5.tsx
  app/lib/realtime.ts
Labels: enhancement, ready to review, ready to deploy

#45 [RPGF-96] Add Funding.JSON For Apply Retro Funding 6
  funding.json
Labels: ready to review, minor change

#67 [Hotfix] Missing retro funding grant for projects in retro funding 6
  app/(white_navbar)/explore/RetroPGF6/[name]/_component/_Project/FundingSection.tsx
  app/lib/utils.ts
  app/types/realtime-api-agora.d.ts
Labels: bug, ready to review

#68 [Hotifx] Fix Typo In EASProjectMetadata Typre
  app/types/realtime-api-agora.d.ts
Labels: bug, ready to review, minor change

#69 [RPGF-98] Fix Component Design Inconsistency
  app/(white_navbar)/explore/RetroPGF2/[name]/_component/_Project/OverviewSection.tsx
  app/(white_navbar)/explore/RetroPGF3/[name]/_component/_Project/OverviewSection.tsx
  app/(white_navbar)/explore/RetroPGF4/[name]/_component/_Project/OverviewSection.tsx
  app/(white_navbar)/explore/RetroPGF5/RetroType5.d.ts
  app/(white_navbar)/explore/RetroPGF5/[name]/_component/_Project/FundingSection.tsx
  app/(white_navbar)/explore/RetroPGF5/[name]/_component/_Project/OverviewSection.tsx
  app/(white_navbar)/explore/RetroPGF5/[name]/_component/_Project/ProjectDetailSection.tsx
  app/(white_navbar)/explore/RetroPGF6/[name]/_component/_Project/FundingSection.tsx
  app/(white_navbar)/explore/RetroPGF6/[name]/_component/_Project/OverviewSection.tsx
  app/(white_navbar)/explore/RetroPGF6/[name]/_component/_Project/ProjectDetailSection.tsx
  app/lib/common.tsx
Labels: bug, ready to review, minor change

#72 [RPGF-102] Add Reward Retro Funding 5
  app/(transparent_navbar)/explore/_component/CardRound5.tsx
  app/(transparent_navbar)/explore/page.tsx
  app/(white_navbar)/explore/RetroPGF5/RetroType5.d.ts
  app/(white_navbar)/explore/RetroPGF5/[name]/Cpage.tsx
  app/(white_navbar)/explore/RetroPGF5/[name]/_component/_Project/ProjectDetailSection.tsx
  app/(white_navbar)/explore/RetroPGF5/[name]/page.tsx
  app/(white_navbar)/explore/RetroPGF5/_component/DynamicCard.tsx
  app/(white_navbar)/explore/RetroPGF5/_component/Tab/ProjectTab.tsx
  app/(white_navbar)/explore/RetroPGF5/page.tsx
  app/component/Card/RetroCardRound5.tsx
  public/static/rpgf5/dummy_rpgf5.json
  public/static/rpgf5/rpgf5.json
Labels: enhancement, ready to review, interface design
